version: '3.8'

services:
  binance-converter-backend:
    image: emil11078/binance-converter-backend:latest
    environment:
      - GRPC_PORT=$BINANCE_CONVERTER_BACKEND_GRPC_PORT
      - POSTGRES_USER_DB_HOST=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_HOST
      - POSTGRES_USER_DB_PORT=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PORT
      - POSTGRES_USER_DB_USER_NAME=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_USER_NAME
      - POSTGRES_USER_DB_PASSWORD=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PASSWORD
      - POSTGRES_USER_DB_NAME=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_NAME
    restart: always
    networks:
      binance-converter:
        aliases:
          - backend
    depends_on:
      - migrations

  migrations:
    image: migrate/migrate
    networks:
      - binance-converter
    volumes:
      - ./migrations:/migrations
    environment:
      - USER_DB_USER_NAME=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_USER_NAME
      - USER_DB_PASSWORD=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PASSWORD
      - USER_DB_NAME=$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_NAME
    command: [ "-path", "/migrations", "-database",
               "postgres://$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_USER_NAME:$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PASSWORD@database:5432/$BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_NAME?sslmode
               =disable", "up" ]

networks:
  binance-converter:
    name: binance-converter