name: Staging

on:
  push:
    branches: [ feature/setting-deploy-to-server ]

  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: get deps
        run: go mod download

      - name: fetch numary control
        uses: actions/download-artifact@v3
        with:
          name: docs-dist
          path: docs/

      - name: Run test
        run: go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...

  build-image:
    name: 'Build and push docker image'
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: emil11078/binance-converter-backend:latest
          platforms:
            linux/arm/v7

  deploy:
    name: 'Deploy to server'
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: deploy to raspberry
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          username: $SSH_USERNAME
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd thing-repository
            docker-compose down
            export BINANCE_CONVERTER_BACKEND_GRPC_PORT=$GRPC_PORT
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_HOST=$POSTGRES_USER_DB_HOST
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PORT=$POSTGRES_USER_DB_PORT
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_USER_NAME=$POSTGRES_USER_DB_NAME
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PASSWORD=${{ secrets.POSTGRES_USER_DB_PASSWORD }}
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_NAME=$POSTGRES_USER_DB_USER_NAME
            docker-compose up